name: "FTPDeployAction"
author: Gabriel Mendonça
description: "Automatizar deploy de projeto por FTP."
inputs:
  hostname: 
    description: 'FTP Hostname'
    required: true
  
  username:
    description: 'FTP User'
    required: true

  password: 
    description: 'FTp Password'
    required: true

  localDir: 
    description: 'Diretório local'
    required: false
    default: '.'
  
  remoteDir:
    description: "Diretório remoto"
    required: false
    default: '.'
runs: 
  using: "composite"
  steps:
    - run: echo "Connect in FTP Server ${{ inputs.hostname }}"
      shell: bash
